# Generated by Django 5.2 on 2025-04-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productcategory_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
