# Generated by Django 5.2 on 2025-04-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orderitems_order_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='_default_address',
            field=models.BooleanField(default=False),
        ),
    ]
