# Generated by Django 5.2 on 2025-04-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customeraddress__default_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='_default_address',
            new_name='default_address',
        ),
    ]
