# Generated by Django 5.2 on 2025-04-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
