# Generated by Django 5.2.5 on 2025-09-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_file',
            field=models.FileField(null=True, upload_to='product_files'),
        ),
    ]
