# Generated by Django 5.2.5 on 2025-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='downloads',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
