# Generated by Django 5.2.5 on 2025-09-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
