# Generated by Django 5.2.5 on 2025-09-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_usd_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
