# Generated by Django 5.2.5 on 2025-09-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_usd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
