# Generated by Django 5.2.5 on 2025-10-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_vendor_mobile_vendor_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='vendor_imgs/'),
        ),
    ]
