# Generated by Django 5.2.5 on 2025-10-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_vendor_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='mobile',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
